config/routes.rb
CoachPortal::Application.routes.draw do
  resources :appointment_types

  resources :topics

  resources :box_links

  match '/search_result' => 'extranet/learners#search_result', :as => :search_result
  match 'show_events_by_date/:event_date' => 'extranet/events#show_events_by_date'
  match 'homes/:action' => 'extranet/homes#(?i-mx:[a-z_]+)'
  match '/learner_details' => 'extranet/learners#learner_details', :as => :learner_details
  match '/show_reason_in_sub_report' => 'substitution#show_reason_in_sub_report', :as => :show_reason_in_sub_report
  match '/consumables_report' => 'support_user_portal/licenses#consumables_report', :as => :consumables_report
  match '/grandfathering_report' => 'support_user_portal/licenses#grandfathering_report', :as => :grandfathering_report
  match '/get_grandfathering_report' => 'support_user_portal/licenses#get_grandfathering_report'
  match '/download_grandfathering_report_csv' => 'support_user_portal/licenses#download_grandfathering_report_csv'
  match 'save_topics' => 'topics#save_topics', :as => :save_topics
  match 'fetch_topics' => 'topics#fetch_topics', :as => :fetch_topics
  scope :module => "extranet" do
    match 'learners/my_calendar' => 'learners#my_calendar'
    match 'events/calendar' => 'events#calendar'
    resources :learners
    resources :homes
    resources :roles
    resources :links
    resources :events
    resources :announcements
    resources :resources
    match 'learners/:action' => 'learners#(?i-mx:[a-z_]+)'
    match 'announcements/:action' => 'announcements#(?i-mx:[a-z_]+)'
    match 'events/:action' => 'events#(?i-mx:[a-z_]+)'
    match 'roles/:action' => 'roles#(?i-mx:[a-z_]+)'
    match 'links/:action' => 'links#(?i-mx:[a-z_]+)'
    match '/profile' => 'homes#view_profile', :as => :profile
    match 'homes/audit_logs' => 'homes#audit_logs', :as => :home_audit_logs
    match 'homes/track_users' => 'homes#track_users', :as => :home_track_users
    match 'homes/admin_dashboard' => 'homes#admin_dashboard', :as => :home_admin_dashboard
    match 'homes/release_lock' => 'homes#release_lock', :as => :home_release_lock
    match 'homes/simulate_delayed_job' => 'homes#simulate_delayed_job', :as => :home_simulate_delayed_job
    match 'homes/set_global_settings' => 'homes#set_global_settings', :as => :home_set_global_settings
    match 'selected_learner_chat_history' => 'learners#selected_learner_chat_history', :as => :selected_chat_history
    match 'detailed_chat_history' => 'learners#detailed_chat_history', :as => :detailed_chat_history
    resources :regions
    match 'regions/:action' => 'regions#(?i-mx:[a-z_]+)'
    resources :learners, :only => [:show] do
      member do
        get :rworld_social_app_info
      end
    end
  end
  match '/sync_eschool_csp_data' => 'application#sync_eschool_csp_data', :as => :sync_eschool_csp_data
  match '/course_info_detail' => 'extranet/learners#course_info_detail', :as => :course_info_detail
  match '/audit_logs' => 'extranet/learners#audit_logs', :as => :audit_logs
  match '/learner/:id(/learner_studio_history/:view_access)' => 'extranet/learners#learner_studio_history', :as => :learner_studio_history
  match 'learner/:id/change_password' => 'extranet/learners#change_password', :as => :change_password
  match 'resources/:action' => 'extranet/resources#(?i-mx:[a-z_]+)'
  match 'resource/:id/download_file' => 'extranet/resources#download_file', :as => :download_file
  match 'get_learner_details' => 'application#get_learner_details', :as => :get_learner_details
  match 'update_aria_session_with_slot_id' => 'application#update_aria_session_with_slot_id', :as => :update_aria_session_with_slot_id
  match 'lotus_real_time_data' => 'lotus#lotus_real_time_data', :as => :lotus_real_time_data
  match 'last_5_logins' => 'lotus#last_5_logins', :as => :last_5_logins
  match 'logged_in_history' => 'extranet/learners#logged_in_history', :as => :logged_in_history
  match 'about_lotus_data' => 'lotus#about_lotus_data', :as => :about_lotus_data
  match 'about_report_data' => 'report#about_report_data', :as => :about_report_data
  match 'learner_search_info' => 'extranet/learners#learner_search_info', :as => :learner_search_info
  match 'reflex_coach_details' => 'lotus#reflex_coach_details', :as => :reflex_coach_details
  match 'reflex_coach_scheduled_details' => 'lotus#reflex_coach_scheduled_details', :as => :reflex_coach_scheduled_details
  match 'reflex_learner_details' => 'lotus#reflex_learner_details', :as => :reflex_learner_details
  match 'activate_deactivate_license' => 'support_user_portal/licenses#activate_deactivate_license', :as => :activate_deactivate_license
  match 'learners_waiting_details' => 'lotus#learners_waiting_details', :as => :learners_waiting_details
  match 'application-status' => 'application#application_status', :as => :application_status
  match 'substitutions_alert' => 'substitution#substitutions_alert', :as => :substitutions_alert
  match 'application_configuration' => 'application#application_configuration', :as => :application_configuration
  match 'schedules/' => 'schedules#index', :as => :schedules
  match 'master-scheduler/' => 'schedules#index', :as => :master_scheduler
  match 'schedules/:language/' => 'schedules#language_schedules', :as => :language
  match 'schedules/:language/:village/' => 'schedules#language_schedules', :as => :language_and_village
  match 'schedules/:language/:village/:date/' => 'schedules#language_schedules', :as => :language_and_village_and_start_date
  match 'schedules/:language/:village/:date/:classroom_type' => 'schedules#language_schedules', :as => :language_and_village_and_start_date
  match 'slots/:language_id/:village_id/:start_time/' => 'schedules#slot_info', :as => :slot_info
  match 'create_session/:lang_identifier/:ext_village_id/:start_time' => 'schedules#create_session', :as => :create_session
  match 'schedules_coach_availability/:language/:coach/:date' => 'schedules#coach_availability_for_week', :as => :coach_availability
  match 'save_local_session' => 'schedules#save_local_session', :as => :save_local_session
  match 'extra_session_reflex/:language/:ext_village_id/:start_time' => 'schedules#extra_session_reflex', :as => :extra_session_reflex
  match 'save_extra_session' => 'schedules#save_extra_session', :as => :save_extra_session
  match 'delete_local_session' => 'schedules#delete_local_session', :as => :delete_local_session
  match 'edit_session' => 'schedules#edit_session', :as => :edit_session
  match 'remove_lotus_session' => 'schedules#remove_lotus_session', :as => :remove_lotus_session
  match 'edit_extra_session' => 'schedules#edit_extra_session', :as => :edit_extra_session
  match 'edit_extra_session_totale' => 'schedules#edit_extra_session_totale', :as => :edit_extra_session_totale
  match 'push_sessions_to_eschool' => 'schedules#push_sessions_to_eschool', :as => :push_sessions_to_eschool
  match 'save_assign_sub' => 'schedules#save_assign_sub', :as => :save_assign_sub
  match 'edit_extra_session_reflex' => 'schedules#edit_extra_session_reflex', :as => :edit_extra_session_reflex
  match 'update_extra_session_reflex' => 'schedules#update_extra_session_reflex', :as => :update_extra_session_reflex
  match 'edit_reflex_session_details' => 'schedules#edit_reflex_session_details', :as => :edit_reflex_session_details
  match 'save_edited_session' => 'schedules#update_session', :as => :save_edited_session
  match 'cancel_totale_session' => 'schedules#cancel_totale_session', :as => :cancel_totale_session
  match 'view_session_details' => 'schedules#view_session_details', :as => :view_session_details
  match 'get_learner_info' => 'schedules#get_learner_info', :as => :get_learner_info
  match 'check_recurrence_end_date' => 'schedules#check_recurrence_end_date', :as => :check_recurrence_end_date
  match 'availability' => 'availability#index', :as => :index
  match 'availability/:coach_id/' => 'availability#index', :as => :index
  match 'availability/:coach_id/:template_id' => 'availability#index', :as => :index
  match 'load_template' => 'availability#load_template', :as => :load_template
  match 'save_template' => 'availability#save_template', :as => :save_template
  match 'approve_template' => 'availability#approve_template', :as => :approve_template
  match 'delete_template' => 'availability#delete_template', :as => :delete_template
  match 'coach_scheduler/' => 'coach_scheduler#index', :as => :index
  match 'export_schedules_in_csv/:start_date_to_export' => 'coach_scheduler#export_schedules_in_csv', :as => :export_schedules_in_csv
  match 'coach_scheduler/:language/' => 'coach_scheduler#index', :as => :language
  match 'coach_scheduler/:language/:coach/' => 'coach_scheduler#index', :as => :language_coach
  match 'coach_scheduler/:language/:coach/:filter_language/' => 'coach_scheduler#index', :as => :language_coach_filter_language
  match 'coach_scheduler/:language/:coach/:filter_language/:date/' => 'coach_scheduler#index', :as => :language_coach_filter_language_date
  match 'coaches_for_given_language/:language/' => 'coach_scheduler#coaches_for_given_language', :as => :coaches_for_given_language
  match 'languages_for_given_language_filter' => 'schedules#languages_for_given_language_filter', :as => :languages_for_given_language_filter
  match 'topic_for_cefr_and_given_language/:language/:cefrLevel/' => 'coach_scheduler#topic_for_cefr_and_given_language', :as => :topic_for_cefr_and_given_language
  match 'create_session_form_in_coach_scheduler' => 'coach_scheduler#create_session_form_in_coach_scheduler', :as => :create_session_form_in_coach_scheduler
  match 'aria_launch_url' => 'application#aria_launch_url', :as => :aria_launch_url
  match 'create_eschool_session_from_coach_scheduler' => 'coach_scheduler#create_eschool_session_from_coach_scheduler', :as => :create_eschool_session_from_coach_scheduler
  match 'coach_session_details/:start_time/:coach_id' => 'coach_scheduler#coach_session_details', :as => :coach_session_details_manager

app/models/region.rb
# == Schema Information
#
# Table name: regions
#
#  id         :integer(4)      not null, primary key
#  name       :string(255)     
#  created_at :datetime        
#  updated_at :datetime        
#

# == Schema Information
#
# Table name: regions
#
#  id         :integer(4)      not null, primary key
#  name       :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Region < ActiveRecord::Base
  audit_logged
  validates_presence_of :name
  validates_uniqueness_of :name, :case_sensitive => false
  validates_format_of  :name, :with => /^[a-zA-Z\-\ ]*?$/, :message => " should contain only alphabets and hyphen"
  has_many :announcements
  has_many :events
  has_many :coaches, :order => 'trim(full_name)'

  class << self
    def all_sorted_by_name
      Region.all.sort_by(&:name)
    end

    def options
      all_sorted_by_name.map {|l| [l.name.to_s, l.id] }
    end
  end
end

app/helpers/manager_portal_helper.rb
module ManagerPortalHelper
  def append_mm(hours_array)
    hours_array.collect{|x| x < 10 ? "0" + x.to_s + ":00" : x.to_s + ":00"}
  end

  def left_navigation_items
    lnav = []
    if manager_logged_in?
      lnav << {:link_text => _('Assign_CoachesBA50525D'),
        :selected_on => {'manager_portal' => ['assign_coaches']},
        :url_options => hash_for_assign_coaches_path}
      lnav << {:link_text => _('Manage_Languages5254C1D6'),
        :selected_on => {'manager_portal' => ['manage_languages']},
        :url_options => hash_for_manage_languages_path}
#      lnav << {:link_text => _('ConfigurationsCE781201'),
#        :selected_on => {'manager_portal' => ['configurations']},
#        :url_options => hash_for_configurations_path}
#      lnav << {:link_text => _('Create_Session85D580AB'),
#        :selected_on => {'manager_portal' => ['create_eschool_session']},
#        :url_options => hash_for_create_eschool_session_path}
      lnav << {:link_text => _('Cancel_SessionsD8C368A1'),
        :selected_on => {'manager_portal' => ['cancel_eschool_sessions']},
        :url_options => hash_for_cancel_eschool_sessions_path}
      lnav << {:link_text => _('Create_Coaches9182421A'),
        :selected_on => {'coach' => ['create_coach']},
        :url_options => hash_for_create_coach_path}
    end
    lnav
  end

  def currently_selected_left_nav_item
    found_nav = left_navigation_items.detect do |nav|
      nav[:selected_on].any? do |cont, actions|
        (params[:controller] == cont) && ((actions == :all) || actions.include?(params[:action]))
      end
    end
    found_nav ? found_nav : nil
  end

  #Converts "Advanced English" to advanced_english
  def classify(text)
    text.downcase.gsub(" ", "_")
  end
  
end

app/views/manager_portal/_coach_languages.html.erb
<%= lang %>

app/views/manager_portal/_coach_time_off_table.html.erb
<%= stylesheet_link_tag "html_table" %>
<%= javascript_include_tag "html_table" %>
<div id ="time_off_table_div"><br>
  <%if @time_off_data && @time_off_data.size > 0 %>
  <table class="table_list scrollTable" id="time_off_table">
  <thead class="fixedHeader ">
    <tr>
      <th class = 'old_th150'>Name</th>
      <th class = 'old_th110'>Hub City</th>
      <th class = 'old_th140'>Start Date</th>
      <th class = 'old_th140'>End Date</th>
      <th class = 'old_th60'>Duration</th>
      <th class = 'old_th80'>Status</th>
      <th class = 'old_th80'>Affected<br> Session(s)*</th>
      <th class = 'old_th134'>Action</th>
    </tr>
  </thead>
   <tbody class="scrollContent">
    <% @time_off_data.each do |t| %>
      <tr id = "<%= t[:time_off_id] %>" >
        <td id = "<%= t[:coach_id]%>" class = 'tb150' style = 'border-bottom: 1px solid #D3EDF9; color: #007AAF'  onclick = 'get_languages(this)'><a><%= t[:coach_name] %> </a></td>
        <td class = 'tb110'><%= t[:coach_region] %></td>
        <td class = 'tb140'><%= t[:time_off_start] %></td>
        <td class = 'tb140'><%= t[:time_off_end] %></td>
        <td class = 'tb60'><%= t[:duration] %></td>
        <td class = 'tb80' id = "status_<%= t[:time_off_id] %>"><%= t[:time_off_status] %></td>
        <td class = 'tb80'><%= t[:affected_count] %></td>
        <td class = 'tb117'>
          <% if t[:action] == "links" %> 
          <a href='javascript:void(0);' class='approve_timeoff'>Approve</a> | <a href='javascript:void(0);' class='approve_timeoff'>Deny</a>
          <% elsif t[:action] == "text" %>
            Approve | Deny
          <% end %>
         </td>
      </tr>
    <% end %>
      </tbody>

</table>
<div class = 'top_padding10'><span class = 'font_size75'> <%= ' Affected Sesions - # of Sessions Scheduled, Cancelled or Substituted' %> </span></div>
  <%else%>
  <div> <p>There are currently no time off reports.</p> </div>
  <%end%>
  <script type="text/javascript">
    jQuery(document).ready(function() {
      if(<%=@time_off_data.size%> == 0){jQuery('#csv_id').hide();}
    }); 
  </script>  

app/views/manager_portal/_coaches_list.html.erb
<%= select_tag 'coach_id', options_for_coaches, {:class => "dropdown",  :disabled => true} %>

app/views/manager_portal/_grid_item.html.erb
<%= render :partial => 'grid_left_half', :locals => {:data => data, :day => day, :hour => hour} %>

<% facebox 'coach_selector_popup?day='+day.to_s+'&date='+(@start_of_that_week + day.days).strftime('%B %d, %Y')+'&hour='+hour.to_s+'&lang_identifier='+@language_identifier+'&classes='+data[:classes].to_s+'&avg_attendance='+data[:avg_attendance].to_s,
  :id => 'link['+day.to_s+']['+hour.to_s+']',
  :if => (data[:committed_coaches]+data[:available_coaches] != 0) do %>
  <div class ="right_inner_element right_inner_color_<%= data[:color_code] %>">
    <% if data[:warning_code] == 'yellow' %>
      <div id="yellows<%=day%><%=hour%>">
        <%=  image_tag('warning_yellow.png', :alt => "Warning", :title => "There are not enough Coaches scheduled or available to match the number of sessions held historically at this time.") %>
      </div>
    <% elsif data[:warning_code] == 'red' %>
      <div id="reds<%=day%><%=hour%>">
        <%=  image_tag('warning_red.png', :alt => "Warning", :title => "There are scheduled sessions outside of tech support hours.") %>
      </div>
    <% end %>
  </div>
<% end %>

<!-- DO NOT MOVE THE FOLLOWING SCRIPT TO APPLICATION.JS -->
<script type="text/javascript">
  jQuery(document).ready(function($) {
    var link_div = document.getElementById('link[<%= day %>][<%= hour %>]');
    jQuery(link_div).facebox();
  })
</script>

app/views/manager_portal/_remove_lotus_session_confirmation.html.erb
<% form_tag remove_lotus_session_path(:coach_session_id => @coach_session.id, :time => @time,
  :lang_identifier => @lang_identifier, :current_coach_id => @coach.id) do -%>
  <div id="remove-lotus-session-form">
    <div>Are you sure you want to remove this session?</div>
    <input class="button medium_button" type="submit" value="Yes" />
    <input class="button medium_button" type="submit" value="No" onclick="jQuery('#remove-lotus-session-confirmation').slideUp();return false;" />
  </div>
<% end -%>

app/views/manager_portal/_select_coach.html.erb
<div class="label">Select Coach</div>
<div class="value"><%= select_tag 'user_name', options_for_coaches(@selected_language, 'user_name', 'full_name'), :onchange => "getMaxQualOfThisCoach();", :disabled => true %>
  <span id="max_qual_of_this_coach"></span>
</div>

<script type="text/javascript">
  function getMaxQualOfThisCoach() {
    if($('user_name').value == '') {
      $('max_qual_of_this_coach').hide();
      alert("Please Select a coach");
      return;
    }
    new Ajax.Updater('max_qual_of_this_coach', '/max_qual_of_coach/' + jQuery('#user_name').val() + '/' + jQuery('#lang_identifier').val(),
    {asynchronous:true, evalScripts:true, method:'get',
      onComplete:function(request){
        $('max_qual_of_this_coach').show();
      },
      onSuccess:function(request){}
    });
  }
</script>

app/views/manager_portal/assign_coaches.html.erb
<% if @coaches.any? -%>
  <p>Select coaches to be assigned under you:</p>
  <%= form_tag assign_coaches_path, :id => 'assign-coaches' do -%>
    <div class="coach_list">
      <% @coaches.each do |coach| -%>
        <p><%= check_box_tag "coach_ids[]", coach.id, false, :class => 'valign-middle' -%><b><%= coach.display_name -%></b></p>
      <% end -%>
    </div>
    <br style="clear:both" />
    <input type="submit" class="btn" value="Assign" />
  <% end -%>
<% else %>
  <p class="notice">All coaches are assigned under appropriate managers.</p>
<% end -%>

<br/>
<%= form_tag assign_coaches_path, :id => 'assign-coaches2' do -%>
  Coach Manager <%= select_tag :coach_manager, options_for_managers %>
  <input type="submit" class="btn" value="Get Coaches" />
<% end -%>
<br />
<% if @assigned_coaches.any? %> 
  <%= form_tag assign_coaches_path, :id => 'assign-coaches1' do -%>
    <div class="coach_list">
      <% @assigned_coaches.each do |assigned_coach| -%>
        <p><%= check_box_tag "coach_ids[]", assigned_coach.id, false, :class => 'valign-middle' -%>
          <b><%= assigned_coach.display_name -%></b></p>
      <% end -%>
    </div>
    <br style="clear:both" />
    Reassign to  : <%= select_tag :manager_id, options_for_other_managers %>
    <input type="submit" class="btn" value="OK" onClick="return handleReAssignCoaches();" />
  <% end -%>
<% else %>
  <p>No Coaches present under <b><%= @coach_manager ? @coach_manager.user_name : current_manager.user_name %></b></p>
<% end %>

app/views/manager_portal/coach_time_off.html.erb
<div id="coach_report">
  <span class = "bold-font"><%= "Today's Date" -%>:</span>
  <span class="left-space" style="font-weight: normal;"><%= get_today_date %> </span>
  <span id="report_generated_for"></span>
  <div class="selection_container">
    <%= form_tag('/get_time_off_ui', :remote => true) do -%>
      <span class="selector">
        <%= select_tag :lang_identifier, options_for_languages(true, nil, true, true) %>
      </span>
      <span class="selector">
        <%= select_tag :region, options_for_region(nil, true, "id".to_sym, "name".to_sym, "Hub City")  %>
      </span>
      <span class="selector">
        <%=  select_tag :timeframe, options_for_duration_for_coach_report %>
      </span>
      <span class="selector">
        <%=  select_tag :time_off_status, options_for_time_off_status %>
      </span>
      
      <span style="float: right"><%= submit_tag 'Generate Report', :onClick => "return getReport()", :disabled => true, :id => "generate_button" %></span>

      <div id="custom_time_select">
        <%= calendar_date_select_tag 'start_date', (Time.now - 1.month).beginning_of_day.strftime("%B %d, %Y %I:%M %p"), :class => 'datetimepicker' %> &nbsp;through&nbsp;
        <%= calendar_date_select_tag 'end_date', (Time.now.end_of_day.strftime("%B %d, %Y %I:%M %p")), :class => 'datetimepicker' %>
      </div>
    <% end %>
  </div>

  <%= image_tag 'big_spinner.gif', :id => 'big_spinner' %>
  <div id ="coach_time_off_data">
    <!-- Contains the time off data -->
  </div>

  <%= form_tag('export_time_off_report', :method=>'get',:id => 'time_off_export_csv_file') do %>
    <%= hidden_field_tag :lang_identifier_hidden %>
    <%= hidden_field_tag :time_off_status_hidden %>
    <%= hidden_field_tag :region_hidden %>
    <%= hidden_field_tag :timeframe_hidden %>
    <%= hidden_field_tag :start_date_hidden%>
    <%= hidden_field_tag :end_date_hidden%>

    <div id="csv_id">
      <span>A complete set of the coach time off report is available as a downloadable .csv file</span>
      <input type="submit" id="time_off_csv" value="EXPORT AS CSV"/>
    </div>
  <% end %>

</div>
<script type="text/javascript">

  getGenerateRange();
  jQuery('#lang_identifier, #timeframe').change(function(){
    if(jQuery('#lang_identifier').val() == "" || jQuery('#timeframe').val() == "Select a Timeframe")
      jQuery("#generate_button").attr("disabled", "disabled");
    else
      jQuery("#generate_button").removeAttr("disabled");

    if(jQuery('#timeframe').val() == "Custom")
      jQuery('#custom_time_select').slideDown("slow");
    else
      jQuery('#custom_time_select').slideUp("slow");
  });

  jQuery('#coach_time_off_data').bind('DOMNodeInserted',function(){
    jQuery('#big_spinner').hide();
    jQuery('#coach_time_off_data').show();
    jQuery('#csv_id').show();
    jQuery('#report_generated_for').show();
  });

  function getReport() {
    start_date  = jQuery('#start_date').val();
    end_date    = jQuery('#end_date').val();
    var date1 = new Date(start_date);
    var date2 = new Date(end_date);
    if((date2 < date1) && jQuery('#timeframe').val() == "Custom") {
      alert("End date must not be less than the start date selected.");
      return false;
    }
    getGenerateRange();
    jQuery('#coach_time_off_data').hide();
    jQuery('#csv_id').hide();
    jQuery('#big_spinner').show();
    jQuery('#lang_identifier_hidden').val(jQuery('#lang_identifier').val());
    jQuery('#region_hidden').val(jQuery('#region').val());
    jQuery('#time_off_status_hidden').val(jQuery('#time_off_status').val());
    jQuery('#timeframe_hidden').val(jQuery('#timeframe').val());
    jQuery('#start_date_hidden').val(jQuery('#start_date').val());
    jQuery('#end_date_hidden').val(jQuery('#end_date').val());
  }


  function getGenerateRange() {
    timeframe = jQuery('#timeframe').val();
    query_params = "timeframe="+timeframe
    start_date  = jQuery('#start_date').val();
    end_date    = jQuery('#end_date').val();
    query_params += "&start_date="+start_date+"&end_date="+end_date // passed everytime.
    if(timeframe != "Select a Timeframe") {
      jQuery.ajax({
        type: 'GET',
        url: '/get_generate_range',
        dataType: "html",
        data: query_params,
        asynchronous: true,
        success: function(data) {
          jQuery('#report_generated_for').html(data);
        },
        error: function() {
          alert('Something went wrong. Please report this problem.');
        }
      });
    }
  }

</script>
<style>
  #start_date, #end_date {
    width: 165px;
  }
</style>

app/views/manager_portal/configurations.html.erb
<p>Configure sessions timeframe based on the language:</p><br />

<%= form_tag configurations_path, :class => 'configure' do -%>
  <p class="head"><em>Language</em><em>Start time</em></p>
  <% @langs.each do |lang| -%>
    <p>
      <em><%= lang.display_name -%></em>
      <%= select_tag "lang_ids[#{lang.id}]", options_for_session_start_time(lang.session_start_time) -%>
    </p>
  <% end -%>
  <input type="submit" class="btn" value="Configure" disabled ="true"/>
<% end -%><br />

<%= form_tag configurations_path, :class => 'configure' do -%>
  <p class="head"><em>Tech Support Window</em></p>
  <p>
    <em>Start Time</em>
    <%= select_tag "tech_support[start_time]", options_for_select(append_mm(HOURS_IN_A_DAY), @tech_support[:start_time]) %>
  </p>
  <p>
    <em>End Time</em>
    <%= select_tag "tech_support[end_time]", options_for_select(append_mm(HOURS_IN_A_DAY), @tech_support[:end_time]) %>
  </p>
  <input type="submit" class="btn" value="Set Tech Support Window" />
<% end -%><br />

<%= form_tag configurations_path, :class => 'configure' do -%>
  <p class="head"><em>Adobe Maintenance Window</em></p>
  <p>
    <em>Start Time</em>
    <%= select_tag "adobe[start_day]", options_for_select(WEEKDAY_NAMES, @adobe[:start_day]) %>
    <%= select_tag "adobe[start_time]", options_for_select(append_mm(HOURS_IN_A_DAY), @adobe[:start_time]) %>
  </p>
  <p>
    <em>End Time</em>
    <%= select_tag "adobe[end_day]", options_for_select(WEEKDAY_NAMES, @adobe[:end_day]) %>
    <%= select_tag "adobe[end_time]", options_for_select(append_mm(HOURS_IN_A_DAY), @adobe[:end_time]) %>
  </p>
  <input type="submit" class="btn" value="Set Adobe Maintenance Window" />
<% end -%><br />

<p><b>Note:</b> All Times in EST</p>

app/views/manager_portal/manage_languages.html.erb
<p>Select languages to be managed by you:</p>
<%= form_tag manage_languages_path, :id => 'assign-langs' do -%>
  <div class="lang_list">
    <% @langs.each do |lang| -%>
      <p><%= check_box_tag "lang_ids[]", lang.id, false, :class => 'valign-middle' -%><b><%= lang.display_name -%></b></p>
    <% end -%>
  </div>
  <br style="clear:both" />
  <input type="submit" class="btn" value="Assign" />
<% end -%>
<br/>
<% if @assigned_langs.any? -%>
  <p class="clear:left;" >Languages managed by you:</p>
  <table class="language_table">
    <% @assigned_langs.each do |lang| %>
      <tr>
        <td style="width: 190px"><b><%= lang.display_name -%></b></td>
        <td><%= link_to 'Remove', "remove-language?id=#{lang.id}" %></td>
      </tr>
    <% end %>
  </table>

<% end -%>