config/routes.rb
CoachPortal::Application.routes.draw do
  resources :appointment_types

  resources :topics

  resources :box_links

  match '/search_result' => 'extranet/learners#search_result', :as => :search_result
  match 'show_events_by_date/:event_date' => 'extranet/events#show_events_by_date'
  match 'homes/:action' => 'extranet/homes#(?i-mx:[a-z_]+)'
  match '/learner_details' => 'extranet/learners#learner_details', :as => :learner_details
  match '/show_reason_in_sub_report' => 'substitution#show_reason_in_sub_report', :as => :show_reason_in_sub_report
  match '/consumables_report' => 'support_user_portal/licenses#consumables_report', :as => :consumables_report
  match '/grandfathering_report' => 'support_user_portal/licenses#grandfathering_report', :as => :grandfathering_report
  match '/get_grandfathering_report' => 'support_user_portal/licenses#get_grandfathering_report'
  match '/download_grandfathering_report_csv' => 'support_user_portal/licenses#download_grandfathering_report_csv'
  match 'save_topics' => 'topics#save_topics', :as => :save_topics
  match 'fetch_topics' => 'topics#fetch_topics', :as => :fetch_topics
  scope :module => "extranet" do
    match 'learners/my_calendar' => 'learners#my_calendar'
    match 'events/calendar' => 'events#calendar'
    resources :learners
    resources :homes
    resources :roles
    resources :links
    resources :events
    resources :announcements
    resources :resources
    match 'learners/:action' => 'learners#(?i-mx:[a-z_]+)'
    match 'announcements/:action' => 'announcements#(?i-mx:[a-z_]+)'
    match 'events/:action' => 'events#(?i-mx:[a-z_]+)'
    match 'roles/:action' => 'roles#(?i-mx:[a-z_]+)'
    match 'links/:action' => 'links#(?i-mx:[a-z_]+)'
    match '/profile' => 'homes#view_profile', :as => :profile
    match 'homes/audit_logs' => 'homes#audit_logs', :as => :home_audit_logs
    match 'homes/track_users' => 'homes#track_users', :as => :home_track_users
    match 'homes/admin_dashboard' => 'homes#admin_dashboard', :as => :home_admin_dashboard
    match 'homes/release_lock' => 'homes#release_lock', :as => :home_release_lock
    match 'homes/simulate_delayed_job' => 'homes#simulate_delayed_job', :as => :home_simulate_delayed_job
    match 'homes/set_global_settings' => 'homes#set_global_settings', :as => :home_set_global_settings
    match 'selected_learner_chat_history' => 'learners#selected_learner_chat_history', :as => :selected_chat_history
    match 'detailed_chat_history' => 'learners#detailed_chat_history', :as => :detailed_chat_history
    resources :regions
    match 'regions/:action' => 'regions#(?i-mx:[a-z_]+)'
    resources :learners, :only => [:show] do
      member do
        get :rworld_social_app_info
      end
    end
  end
  match '/sync_eschool_csp_data' => 'application#sync_eschool_csp_data', :as => :sync_eschool_csp_data
  match '/course_info_detail' => 'extranet/learners#course_info_detail', :as => :course_info_detail
  match '/audit_logs' => 'extranet/learners#audit_logs', :as => :audit_logs
  match '/learner/:id(/learner_studio_history/:view_access)' => 'extranet/learners#learner_studio_history', :as => :learner_studio_history
  match 'learner/:id/change_password' => 'extranet/learners#change_password', :as => :change_password
  match 'resources/:action' => 'extranet/resources#(?i-mx:[a-z_]+)'
  match 'resource/:id/download_file' => 'extranet/resources#download_file', :as => :download_file
  match 'get_learner_details' => 'application#get_learner_details', :as => :get_learner_details
  match 'update_aria_session_with_slot_id' => 'application#update_aria_session_with_slot_id', :as => :update_aria_session_with_slot_id
  match 'lotus_real_time_data' => 'lotus#lotus_real_time_data', :as => :lotus_real_time_data
  match 'last_5_logins' => 'lotus#last_5_logins', :as => :last_5_logins
  match 'logged_in_history' => 'extranet/learners#logged_in_history', :as => :logged_in_history
  match 'about_lotus_data' => 'lotus#about_lotus_data', :as => :about_lotus_data
  match 'about_report_data' => 'report#about_report_data', :as => :about_report_data
  match 'learner_search_info' => 'extranet/learners#learner_search_info', :as => :learner_search_info
  match 'reflex_coach_details' => 'lotus#reflex_coach_details', :as => :reflex_coach_details
  match 'reflex_coach_scheduled_details' => 'lotus#reflex_coach_scheduled_details', :as => :reflex_coach_scheduled_details
  match 'reflex_learner_details' => 'lotus#reflex_learner_details', :as => :reflex_learner_details
  match 'activate_deactivate_license' => 'support_user_portal/licenses#activate_deactivate_license', :as => :activate_deactivate_license
  match 'learners_waiting_details' => 'lotus#learners_waiting_details', :as => :learners_waiting_details
  match 'application-status' => 'application#application_status', :as => :application_status
  match 'substitutions_alert' => 'substitution#substitutions_alert', :as => :substitutions_alert
  match 'application_configuration' => 'application#application_configuration', :as => :application_configuration
  match 'schedules/' => 'schedules#index', :as => :schedules
  match 'master-scheduler/' => 'schedules#index', :as => :master_scheduler
  match 'schedules/:language/' => 'schedules#language_schedules', :as => :language
  match 'schedules/:language/:village/' => 'schedules#language_schedules', :as => :language_and_village
  match 'schedules/:language/:village/:date/' => 'schedules#language_schedules', :as => :language_and_village_and_start_date
  match 'schedules/:language/:village/:date/:classroom_type' => 'schedules#language_schedules', :as => :language_and_village_and_start_date
  match 'slots/:language_id/:village_id/:start_time/' => 'schedules#slot_info', :as => :slot_info
  match 'create_session/:lang_identifier/:ext_village_id/:start_time' => 'schedules#create_session', :as => :create_session
  match 'schedules_coach_availability/:language/:coach/:date' => 'schedules#coach_availability_for_week', :as => :coach_availability
  match 'save_local_session' => 'schedules#save_local_session', :as => :save_local_session
  match 'extra_session_reflex/:language/:ext_village_id/:start_time' => 'schedules#extra_session_reflex', :as => :extra_session_reflex
  match 'save_extra_session' => 'schedules#save_extra_session', :as => :save_extra_session
  match 'delete_local_session' => 'schedules#delete_local_session', :as => :delete_local_session
  match 'edit_session' => 'schedules#edit_session', :as => :edit_session
  match 'remove_lotus_session' => 'schedules#remove_lotus_session', :as => :remove_lotus_session
  match 'edit_extra_session' => 'schedules#edit_extra_session', :as => :edit_extra_session
  match 'edit_extra_session_totale' => 'schedules#edit_extra_session_totale', :as => :edit_extra_session_totale
  match 'push_sessions_to_eschool' => 'schedules#push_sessions_to_eschool', :as => :push_sessions_to_eschool
  match 'save_assign_sub' => 'schedules#save_assign_sub', :as => :save_assign_sub
  match 'edit_extra_session_reflex' => 'schedules#edit_extra_session_reflex', :as => :edit_extra_session_reflex
  match 'update_extra_session_reflex' => 'schedules#update_extra_session_reflex', :as => :update_extra_session_reflex
  match 'edit_reflex_session_details' => 'schedules#edit_reflex_session_details', :as => :edit_reflex_session_details
  match 'save_edited_session' => 'schedules#update_session', :as => :save_edited_session
  match 'cancel_totale_session' => 'schedules#cancel_totale_session', :as => :cancel_totale_session
  match 'view_session_details' => 'schedules#view_session_details', :as => :view_session_details
  match 'get_learner_info' => 'schedules#get_learner_info', :as => :get_learner_info
  match 'check_recurrence_end_date' => 'schedules#check_recurrence_end_date', :as => :check_recurrence_end_date
  match 'availability' => 'availability#index', :as => :index
  match 'availability/:coach_id/' => 'availability#index', :as => :index
  match 'availability/:coach_id/:template_id' => 'availability#index', :as => :index
  match 'load_template' => 'availability#load_template', :as => :load_template
  match 'save_template' => 'availability#save_template', :as => :save_template
  match 'approve_template' => 'availability#approve_template', :as => :approve_template
  match 'delete_template' => 'availability#delete_template', :as => :delete_template
  match 'coach_scheduler/' => 'coach_scheduler#index', :as => :index
  match 'export_schedules_in_csv/:start_date_to_export' => 'coach_scheduler#export_schedules_in_csv', :as => :export_schedules_in_csv
  match 'coach_scheduler/:language/' => 'coach_scheduler#index', :as => :language
  match 'coach_scheduler/:language/:coach/' => 'coach_scheduler#index', :as => :language_coach
  match 'coach_scheduler/:language/:coach/:filter_language/' => 'coach_scheduler#index', :as => :language_coach_filter_language
  match 'coach_scheduler/:language/:coach/:filter_language/:date/' => 'coach_scheduler#index', :as => :language_coach_filter_language_date
  match 'coaches_for_given_language/:language/' => 'coach_scheduler#coaches_for_given_language', :as => :coaches_for_given_language
  match 'languages_for_given_language_filter' => 'schedules#languages_for_given_language_filter', :as => :languages_for_given_language_filter
  match 'topic_for_cefr_and_given_language/:language/:cefrLevel/' => 'coach_scheduler#topic_for_cefr_and_given_language', :as => :topic_for_cefr_and_given_language
  match 'create_session_form_in_coach_scheduler' => 'coach_scheduler#create_session_form_in_coach_scheduler', :as => :create_session_form_in_coach_scheduler
  match 'aria_launch_url' => 'application#aria_launch_url', :as => :aria_launch_url
  match 'create_eschool_session_from_coach_scheduler' => 'coach_scheduler#create_eschool_session_from_coach_scheduler', :as => :create_eschool_session_from_coach_scheduler
  match 'coach_session_details/:start_time/:coach_id' => 'coach_scheduler#coach_session_details', :as => :coach_session_details_manager

app/views/support_user_portal/learner_access_logs/_basic_studio_info.html.erb
<div class="studio_info" id="studio_info">
  <p class="header">Studio</p>
  <br />
  <% if (!student.attended_session.class.eql? String)%>
    <% unless student.attended_session.blank? %>
      <div class="wide_label_row" style="width:340px;">
        <span class="label">Last Attended Session</span>
      </div>
      <div class="col-1">
        <span><%= name_from_code(student.attended_session.language) %></span><br />
        <span>Coach: <%= student.attended_session.coach? ? student.attended_session.coach : 'N/A' %></span>
      </div>
      <div class="col-2">
        <span>Level <%= student.attended_session.level %> Unit <%= student.attended_session.unit %></span><br />
        <span>Session Rating: <%= link_to get_session_rating(student.attended_session), '#', :id => 'rating_attended' %></span>
      </div>
      <div class="col-3">
        <span><%= (student.attended_session.on).to_time.strftime("%a, %b %d, %Y - %I:%M%p") %></span><br />
        <span>Attendance: <%= link_to student.attended_session.attendance_record, '#', :id => 'attendance_attended' %></span>
      </div>
    <% end %>
  <% end %>
  <% if (!student.skipped_session.class.eql? String)%>
    <% unless student.skipped_session.blank? %>
      <div class="wide_label_row" style="width:340px;">
        <span class="label">Last Skipped Session</span>
      </div>
      <div class="col-1">
        <span><%= name_from_code(student.skipped_session.language) %></span><br />
        <span>Coach: <%= student.skipped_session.coach? ? student.skipped_session.coach : 'N/A' %></span>
      </div>
      <div class="col-2">
        <span>Level <%= student.skipped_session.level %> Unit <%= student.skipped_session.unit %></span><br />
        <span>Session Rating:<%= get_session_rating student.skipped_session %></span>
      </div>
      <div class="col-3">
        <span><%= (student.skipped_session.on).to_time.strftime("%a, %b %d, %Y - %I:%M%p") %></span><br />
        <span>Attendance: <%= link_to student.skipped_session.attendance_record, '#', :id => 'attendance_skipped' %></span>
      </div>
    <% end %>
  <% end %>
  <% if (!student.next_session.class.eql? String)%>
    <% unless student.next_session.blank? %>
      <div class="wide_label_row" style="width:340px;font-weight:bold;">
        <span class="label">Next Scheduled Session</span>
      </div>
      <div class="col-1">
        <span><%= name_from_code(student.next_session.language) %></span><br />
        <span>Coach: <%= student.next_session.coach? ? student.next_session.coach : 'N/A' %></span>
      </div>
      <div class="col-2">
        <span>Level <%= student.next_session.level %> Unit <%= student.next_session.unit %></span><br />
        <span>Session Rating: <%= get_session_rating student.attended_session %></span>
      </div>
      <div class="col-3">
        <span><%= (student.next_session.on).to_time.strftime("%a, %b %d, %Y - %I:%M%p") %></span><br />
        <span>Attendance: <%= link_to student.next_session.attendance_record, '#', :id => 'attendance_next' %></span>
      </div>
    <% end %>
  <% end %>

  <br />
  <div class="float_left padding_top_30" style="width: 40%; clear: both;padding-left:0px;">
    <div class="wide_label_row">
      <span class="label" style="width:180px;">Total Attended sessions</span><span class="formw"><%= student.attended %></span>
    </div>
    <div class="wide_label_row">
      <span class="label" style="width:180px;">Total Skipped sessions</span><span class="formw"><%= student.skipped %></span>
    </div>
  </div>
  <div class="learner_studio_history_link">
    <span class="greyed"><%= link_to_if (student.attended.to_i+student.skipped.to_i !=0) ,"Learner Studio History", studio_history_path(:id => @learner.id) %></span>
  </div>
</div>

app/views/support_user_portal/learner_access_logs/_general_profile_info.html.erb
<div id="general_info">
  <p class="header">General</p><br />
  <div class="separating_line"></div>
  <div class="float_left" style="width:100%">
    <div class="wide_label_row">
      <span class="label">Name</span><span class="formw"><%= get_text(@learner.name) %></span>
    </div>
    <div class="wide_label_row">
      <span class="label">Email</span><span class="formw"><%= get_text(@learner.email) %></span>
    </div>
    <div class="wide_label_row">
      <span class="label">Location</span><span class="formw"><%= get_text(@learner.address_info) %></span>
    </div>
    <div class="wide_label_row">
      <span class="label">GUID</span><span class="formw" style="font-family: monospace; font-size: 12px;" ><%= get_text(@learner.guid) %></span>
    </div>
    <div class="wide_label_row">
      <span class="label">Source</span><span class="formw"><%= get_text(@learner.type) %></span>
    </div>
    <% if @learner.community_user? %>
      <div class="wide_label_row">
        <span class="label">Activated</span><span class="formw"><%= get_text(@learner.activated_at) %></span>
      </div>
    <% end -%>
  </div>
</div>

app/views/support_user_portal/learner_access_logs/_languages.html.erb
<div class="languages" id="languages" >
  <div class="float_left" style="clear:left; width:41%">
    <span class="subheading">Languages</span>
    <div class="wide_label_row">
      <span class="label">TOTALe</span>
      <span class="formw"><%= get_text(@learner.totale_languages_display_name) %></span>
    </div>
    <div class="wide_label_row">
      <span class="label">RWorld</span>
      <span class="formw"><%= get_text(@learner.rworld_display_name) %></span>
    </div>
    <div class="wide_label_row">
      <span class="label">Simbio</span>
      <span class="formw"><%= get_text(@learner.simbio) %></span>
    </div>
  </div>
</div>

app/views/support_user_portal/learner_access_logs/_learners.html.erb
<tr style="line-height:25px">
  <td><%= link_to(highlight_search_result(learners.name, params), learner_path(:id => learners.id)) %></td>
  <td><%= highlight_search_result(learners.email, params) %></td>
  <td><%= learners.type %><%= "(#{learners.subscriptions.to_sentence})" unless learners.subscriptions.blank?  %></td>
</tr>

app/views/support_user_portal/learner_access_logs/_recent_course_info.html.erb
<div id="recent_course_info">
  <p class="header">Course - <%= name_from_code(course_tracking_info["language"]) %></p>
  <br/>
  <div class="float_left" style="width: 67%; clear: both">
    <div class="wide_label_row">
      <span class="label">Highest Water Mark</span><span class="formw" title="Level.Unit.Lesson">
        <%="#{get_number course_tracking_info["high_water_mark"]["level"]}.#{get_number course_tracking_info["high_water_mark"]["unit"]}.#{get_number course_tracking_info["high_water_mark"]["lesson"]}" %>
      </span>
    </div>

    <div class="wide_label_row">
      <span class="label">Most Recent Completed</span><span class="formw" title="Level.Unit.Lesson">
        <%="#{get_number course_tracking_info["last_completed"]["level"]}.#{get_number course_tracking_info["last_completed"]["unit"]}.#{get_number course_tracking_info["last_completed"]["lesson"]}" %>
      </span>
    </div>

    <div class="wide_label_row">
      <span class="label">Last Access</span>
      <span class="formw"><%= get_text course_tracking_info["last_access_time"] %></span>
    </div>
  </div>


  <div class="float_left" style="width: 67%; clear: both; padding-top: 10px;">
    <span class="subheading">Progress per language per level</span><br />
    <%= form_tag({:controller => 'licenses', :action => 'course_info_details'}, :method => :get) do -%>
      <input type="hidden" name="learner" value= <%=  learner.id%> />
      <div class="wide_label_row">
        <span class="label">Language</span><span class="formw"><%= select_tag :lang, options_for_select([course_tracking_info["progressed_languages"]["language"]].flatten.map {|lan| lan["code"]}, course_tracking_info["language"]) %></span>
      </div>
      <div class="wide_label_row">
        <span class="label">Level</span><span class="formw"><%= select_tag :level %></span>
      </div>
      <%= submit_tag "Submit" %>
    <%  end -%>
  </div>

  <div class="float_left path_score_details" style="width: 100%; clear: both; padding-top: 10px;">
    <% if !baffler_path_scores.blank? && !baffler_path_scores["path_scores"].blank? -%>
      <span class="subheading">Path Score Details - <%= name_from_code(course_tracking_info["language"]) %></span>

      <div class="wide_label_row">
        <span class="label">Unit</span><span class="label">Lesson</span><span class="label">Path Type</span><span class="label">Complete</span><span class="label">Date</span>
      </div>

      <% [baffler_path_scores["path_scores"]["path_score"]].flatten.each do |path_score| -%>
        <div class="wide_label_row" style="font-weight: normal !important;">
          <span class="lighter_label"><%= path_score["unit"] %></span>
          <span class="lighter_label"><%= path_score["lesson"] %></span>
          <span class="lighter_label"><%= path_score["path_type"] %></span>
          <span class="lighter_label"><%= path_score["complete"] %></span>
          <span class="lighter_label"><%= path_score["updated_at"] %></span>
        </div>

      <% end -%>
    <% end -%>
  </div>

  <% content_for :inline_javascript do -%>
    <% langs = [course_tracking_info["progressed_languages"]["language"]].flatten
    langs_levels = {}
    langs.each { |lang| langs_levels[lang["code"]] = lang["levels"]["level"] }
    -%>
    SuccessExtranet.TotaleCourseInfo.setLangLevels(<%= langs_levels.to_json %>);
  <% end %>

</div>

app/views/support_user_portal/learner_access_logs/_rworld_lang_info.html.erb
<div class="rworld_lang_info" id="rworld_lang_info">
  <br style="clear: both;"/>
  <span class="subheading">Social Apps</span>
  <br/><br/>
  <% unless baffler_details["social_apps"]["social_app"].blank? -%>
    <div class="outlined_table">
      <table class="se_tab social_apps">
        <tr>
          <th style="text-align:center">Application</th>
          <th style="text-align:center">Name</th>
          <th style="text-align:center">Count</th>
          <th style="text-align:center">Time Spent</th>
        </tr>
        <% [baffler_details["social_apps"]["social_app"]].flatten.each do |s_app| -%>
          <tr>
            <td><%= s_app["identifier"] %></td>
            <td><%= s_app["display_name"] %></td>
            <td style="text-align:right"><%= s_app["count"] %></td>
            <td style="text-align:center"><%= Time.at(s_app["seconds"].to_i).utc.strftime("%H:%M:%S")  %></td>
          </tr>
        <% end %>
        <tr>
          <th></th>
          <th>TOTAL</th>
          <th style="text-align:right"><%= get_text baffler_details["social_apps"]["total"]["count"] %></th>
          <th style="text-align:center"><%= Time.at(baffler_details["social_apps"]["total"]["seconds"].to_i).utc.strftime("%H:%M:%S")  %></th>
        </tr>
      </table>
    </div>
  <% else %>
    <p class="notice">No Social Apps played.</p>
  <% end %>
</div>

app/views/support_user_portal/learner_access_logs/_studio_info.html.erb
<%= render :partial => '/support_user_portal/learner_access_logs/basic_studio_info', :locals =>{:student=> student}%>
<%= render :partial => '/support_user_portal/learner_access_logs/session_feedback', :locals =>{:student=> student}%>
<%= render :partial => '/support_user_portal/learner_access_logs/session_attendance', :locals =>{:student=> student}%>

app/views/support_user_portal/learner_access_logs/community_learner_audit_log_history.html.erb
<div class="form_container">
  <br/>
  <%= link_to "Back to learner's access log page", view_access_log_path(:license_identifier => @learner.email) %>
  <br/>
  <div id="profile">
    <p class="header">Audit log history of <%= "#{@learner.first_name} #{@learner.last_name}" %> </p>
    <br/>
    <% unless audit_logs.blank? %>
      <div class="outlined_table">
        <table>
          <tr>
            <th>Action</th>
            <th>Attribute Name</th>
            <th>Previous Value</th>
            <th>New Value</th>
            <th>Changed By</th>
            <th>IP Address</th>
          </tr>
          <% audit_logs.each do |audit_log| %>
            <tr>
              <td><%= audit_log.action %></td>
              <td><%= audit_log.attribute_name %></td>
              <td><%= audit_log.previous_value %></td>
              <td><%= audit_log.new_value %></td>
              <td><%= audit_log.changed_by %></td>
              <td><%= audit_log.ip_address %></td>
            </tr>
          <% end %>
        </table>
      </div>
    <% else %>
      <p class="notice">No audit log history found.</p>
    <%  end %>
    <p class="header" style="border-bottom:none"></p>
  </div>
</div>

app/views/support_user_portal/learner_access_logs/course_info_detail.html.erb
<div class="form_container">
  <br/>
  <%= link_to "Back to learner's access log page", view_access_log_path(:license_identifier => @learner.email) %>
  <div id="profile">
    <%= render :partial => "/support_user_portal/learner_access_logs/recent_course_info", :locals => { :course_tracking_info => @baffler_course_tracking_info, :learner => @learner, :baffler_path_scores => @baffler_path_scores } if @baffler_course_tracking_info %>
    <p class="header" style="border-bottom:none"></p>
  </div>
</div>
<%# selecting the level using javascript based on the level in the url params. -%>
<% content_for :inline_javascript do -%>
  setTimeout(function(){
    $("level").value = "<%= params[:level] %>";
  }, 2000);
<% end -%>

app/views/support_user_portal/learner_access_logs/learner_studio_history.html.erb
<div class="form_container">
  <div id="profile">
    <div class="student_studio_history" id="student_studio_history">
      <%= link_to "Back to learner's access log page", view_access_log_path(:license_identifier => @learner.email) %>
      <br/>
      <p class="header">Learner Studio History </p>
      <div id="eschool" style="padding:10px">
        <table>
          <% if !student.eschool_sessions.blank? -%>
            <thead>
              <tr>
                <th style="width:150px">Date & Time (EST)</th>
                <th style="width:150px">Learner Date & Time (<%= ActiveSupport::TimeZone[student.time_zone].now.zone %>)</th>
                <th style="width:240px">Language</th>
                <th style="width:75px">Level</th>
                <th style="width:75px">Unit</th>
                <th style="width:100px">Attended</th>
                <th style="width:100px">Mins in Session</th>
                <th style="width:100px">Technical Issues?</th>
              </tr>
            </thead>
            <tbody>
              <% student.eschool_sessions.each do |es| %>
                <tr>
                  <td><%= es.start_time.to_time.in_time_zone("Eastern Time (US & Canada)") %></td>
                  <td><%= es.start_time.to_time.in_time_zone(student.time_zone) %></td>
                  <td><%= name_from_code es.language_code %></td>
                  <td><%= es.level %></td>
                  <td><%= es.unit %></td>
                  <td><%= es.attended == "true" ? "Attended" : es.cancelled == "true" ? "Cancelled" : "Skipped" %></td>
                  <td><%= es.last_seen_at && es.first_seen_at ? difference_of_time_mmss(es.last_seen_at.to_time, es.first_seen_at.to_time) : "--" %></td>
                  <td><%= es.technical_issues == "true" ? "Yes" : "No" %></td>
                </tr>
              <% end %>
            </tbody>
          <% else -%>
            <p class="notice">No studio sessions found for this user.</p>
          <% end -%>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/support_user_portal/learner_access_logs/profile.html.erb
<div class="form_container">
  <%= link_to 'Try a new search', learners_path %>
  <div id="profile">
    <p class="header">Community Profile</p>
    <div id="general">
      <ul class="col1 view">
        <li style="color:#FF9A00;">Public</li>
        <li><label>Email</label> <span><%= @learner.email %></span></li>
        <li><label>First Name</label> <span><%= @learner.first_name %></span></li>
        <li><label>Last Name</label> <span><%= @learner.last_name %></span></li>
        <li><label>Prefered Name</label> <span></span><%= @learner.preferred_name %></li>
        <li><label>Country</label> <span><%= @learner.city %></span></li>
        <li><label>State/Province</label> <span></span></li>
        <li><label>City</label> <span></span></li>
      </ul>
      <ul class="col2 view">
        <li style="color:#FF9A00;">Private</li>
        <li><label>Birthdate</label> <span></span></li>
        <li><label>Gender</label> <span></span></li>
        <li><label>Time Zone</label> <span></span></li>
        <li><label><%= link_to("Last Updated") %></label> <span></span></li>
        <li style="color:#FF9A00;">Languages</li>
        <li><label>TOTALe</label> <span></span></li>
        <li><label>RWorld</label> <span></span></li>
        <li><label>Simbio</label> <span></span></li>
      </ul>
      <ul class="col3">
        <li></li>
      </ul>
    </div>

    <p class="header" style="border-bottom:none"></p>

    <!--
        <p class="header">Studio</p>
        <p class="header">Course - French</p>
        <p class="header">World</p>
        <p class="header">Time spent on Languages</p>
    -->
  </div>
</div>

app/views/support_user_portal/learner_access_logs/show.html.erb
<div class="form_container">
  <%= link_to 'Back to License Details', support_portal_home_path(:license_identifier => @learner.email) %>

  <div id="profile">
    <%= render :partial => "/support_user_portal/learner_access_logs/general_profile_info" %>
    <div id="community_profile">
      <% if @learner.community_user? -%>
        <%= render :partial => "/support_user_portal/learner_access_logs/public_private_info" %>
        <%= render :partial => "/support_user_portal/learner_access_logs/languages" %><br />
      <% end %>
    </div>
    <%= render :partial => "/support_user_portal/learner_access_logs/studio_info", :locals => {:student => @as_a_student} if @as_a_student %>
    <% if @learner.community_user? -%>
      <%= render :partial => "/support_user_portal/learner_access_logs/recent_course_info", :locals => { :course_tracking_info => @baffler_course_tracking_info, :learner => @learner, :baffler_path_scores => nil } if(@baffler_course_tracking_info && !@baffler_course_tracking_info["progressed_languages"].blank?) %>
      <%= render :partial => "/support_user_portal/learner_access_logs/rworld_info", :locals => { :baffler_details => @baffler_details, :social_app_languages => @baffler_social_app_languages, :connections_count => @connections_count } %>
      <%= render :partial => "/support_user_portal/learner_access_logs/time_on_languages", :locals => { :baffler_time_spent_on_languages => @baffler_time_spent_on_languages } unless @baffler_time_spent_on_languages.blank? %>
    <% end %>
    <p class="header" style="border-bottom:none"></p>
  </div>
</div>