config/routes.rb
CoachPortal::Application.routes.draw do
  resources :appointment_types

  resources :topics

  resources :box_links

  match '/search_result' => 'extranet/learners#search_result', :as => :search_result
  match 'show_events_by_date/:event_date' => 'extranet/events#show_events_by_date'
  match 'homes/:action' => 'extranet/homes#(?i-mx:[a-z_]+)'
  match '/learner_details' => 'extranet/learners#learner_details', :as => :learner_details
  match '/show_reason_in_sub_report' => 'substitution#show_reason_in_sub_report', :as => :show_reason_in_sub_report
  match '/consumables_report' => 'support_user_portal/licenses#consumables_report', :as => :consumables_report
  match '/grandfathering_report' => 'support_user_portal/licenses#grandfathering_report', :as => :grandfathering_report
  match '/get_grandfathering_report' => 'support_user_portal/licenses#get_grandfathering_report'
  match '/download_grandfathering_report_csv' => 'support_user_portal/licenses#download_grandfathering_report_csv'
  match 'save_topics' => 'topics#save_topics', :as => :save_topics
  match 'fetch_topics' => 'topics#fetch_topics', :as => :fetch_topics
  scope :module => "extranet" do
    match 'learners/my_calendar' => 'learners#my_calendar'
    match 'events/calendar' => 'events#calendar'
    resources :learners
    resources :homes
    resources :roles
    resources :links
    resources :events
    resources :announcements
    resources :resources
    match 'learners/:action' => 'learners#(?i-mx:[a-z_]+)'
    match 'announcements/:action' => 'announcements#(?i-mx:[a-z_]+)'
    match 'events/:action' => 'events#(?i-mx:[a-z_]+)'
    match 'roles/:action' => 'roles#(?i-mx:[a-z_]+)'
    match 'links/:action' => 'links#(?i-mx:[a-z_]+)'
    match '/profile' => 'homes#view_profile', :as => :profile
    match 'homes/audit_logs' => 'homes#audit_logs', :as => :home_audit_logs
    match 'homes/track_users' => 'homes#track_users', :as => :home_track_users
    match 'homes/admin_dashboard' => 'homes#admin_dashboard', :as => :home_admin_dashboard
    match 'homes/release_lock' => 'homes#release_lock', :as => :home_release_lock
    match 'homes/simulate_delayed_job' => 'homes#simulate_delayed_job', :as => :home_simulate_delayed_job
    match 'homes/set_global_settings' => 'homes#set_global_settings', :as => :home_set_global_settings
    match 'selected_learner_chat_history' => 'learners#selected_learner_chat_history', :as => :selected_chat_history
    match 'detailed_chat_history' => 'learners#detailed_chat_history', :as => :detailed_chat_history
    resources :regions
    match 'regions/:action' => 'regions#(?i-mx:[a-z_]+)'
    resources :learners, :only => [:show] do
      member do
        get :rworld_social_app_info
      end
    end
  end
  match '/sync_eschool_csp_data' => 'application#sync_eschool_csp_data', :as => :sync_eschool_csp_data
  match '/course_info_detail' => 'extranet/learners#course_info_detail', :as => :course_info_detail
  match '/audit_logs' => 'extranet/learners#audit_logs', :as => :audit_logs
  match '/learner/:id(/learner_studio_history/:view_access)' => 'extranet/learners#learner_studio_history', :as => :learner_studio_history
  match 'learner/:id/change_password' => 'extranet/learners#change_password', :as => :change_password
  match 'resources/:action' => 'extranet/resources#(?i-mx:[a-z_]+)'
  match 'resource/:id/download_file' => 'extranet/resources#download_file', :as => :download_file
  match 'get_learner_details' => 'application#get_learner_details', :as => :get_learner_details
  match 'update_aria_session_with_slot_id' => 'application#update_aria_session_with_slot_id', :as => :update_aria_session_with_slot_id
  match 'lotus_real_time_data' => 'lotus#lotus_real_time_data', :as => :lotus_real_time_data
  match 'last_5_logins' => 'lotus#last_5_logins', :as => :last_5_logins
  match 'logged_in_history' => 'extranet/learners#logged_in_history', :as => :logged_in_history
  match 'about_lotus_data' => 'lotus#about_lotus_data', :as => :about_lotus_data
  match 'about_report_data' => 'report#about_report_data', :as => :about_report_data
  match 'learner_search_info' => 'extranet/learners#learner_search_info', :as => :learner_search_info
  match 'reflex_coach_details' => 'lotus#reflex_coach_details', :as => :reflex_coach_details
  match 'reflex_coach_scheduled_details' => 'lotus#reflex_coach_scheduled_details', :as => :reflex_coach_scheduled_details
  match 'reflex_learner_details' => 'lotus#reflex_learner_details', :as => :reflex_learner_details
  match 'activate_deactivate_license' => 'support_user_portal/licenses#activate_deactivate_license', :as => :activate_deactivate_license
  match 'learners_waiting_details' => 'lotus#learners_waiting_details', :as => :learners_waiting_details
  match 'application-status' => 'application#application_status', :as => :application_status
  match 'substitutions_alert' => 'substitution#substitutions_alert', :as => :substitutions_alert
  match 'application_configuration' => 'application#application_configuration', :as => :application_configuration
  match 'schedules/' => 'schedules#index', :as => :schedules
  match 'master-scheduler/' => 'schedules#index', :as => :master_scheduler
  match 'schedules/:language/' => 'schedules#language_schedules', :as => :language
  match 'schedules/:language/:village/' => 'schedules#language_schedules', :as => :language_and_village
  match 'schedules/:language/:village/:date/' => 'schedules#language_schedules', :as => :language_and_village_and_start_date
  match 'schedules/:language/:village/:date/:classroom_type' => 'schedules#language_schedules', :as => :language_and_village_and_start_date
  match 'slots/:language_id/:village_id/:start_time/' => 'schedules#slot_info', :as => :slot_info
  match 'create_session/:lang_identifier/:ext_village_id/:start_time' => 'schedules#create_session', :as => :create_session
  match 'schedules_coach_availability/:language/:coach/:date' => 'schedules#coach_availability_for_week', :as => :coach_availability
  match 'save_local_session' => 'schedules#save_local_session', :as => :save_local_session
  match 'extra_session_reflex/:language/:ext_village_id/:start_time' => 'schedules#extra_session_reflex', :as => :extra_session_reflex
  match 'save_extra_session' => 'schedules#save_extra_session', :as => :save_extra_session
  match 'delete_local_session' => 'schedules#delete_local_session', :as => :delete_local_session
  match 'edit_session' => 'schedules#edit_session', :as => :edit_session
  match 'remove_lotus_session' => 'schedules#remove_lotus_session', :as => :remove_lotus_session
  match 'edit_extra_session' => 'schedules#edit_extra_session', :as => :edit_extra_session
  match 'edit_extra_session_totale' => 'schedules#edit_extra_session_totale', :as => :edit_extra_session_totale
  match 'push_sessions_to_eschool' => 'schedules#push_sessions_to_eschool', :as => :push_sessions_to_eschool
  match 'save_assign_sub' => 'schedules#save_assign_sub', :as => :save_assign_sub
  match 'edit_extra_session_reflex' => 'schedules#edit_extra_session_reflex', :as => :edit_extra_session_reflex
  match 'update_extra_session_reflex' => 'schedules#update_extra_session_reflex', :as => :update_extra_session_reflex
  match 'edit_reflex_session_details' => 'schedules#edit_reflex_session_details', :as => :edit_reflex_session_details
  match 'save_edited_session' => 'schedules#update_session', :as => :save_edited_session
  match 'cancel_totale_session' => 'schedules#cancel_totale_session', :as => :cancel_totale_session
  match 'view_session_details' => 'schedules#view_session_details', :as => :view_session_details
  match 'get_learner_info' => 'schedules#get_learner_info', :as => :get_learner_info
  match 'check_recurrence_end_date' => 'schedules#check_recurrence_end_date', :as => :check_recurrence_end_date
  match 'availability' => 'availability#index', :as => :index
  match 'availability/:coach_id/' => 'availability#index', :as => :index
  match 'availability/:coach_id/:template_id' => 'availability#index', :as => :index
  match 'load_template' => 'availability#load_template', :as => :load_template
  match 'save_template' => 'availability#save_template', :as => :save_template
  match 'approve_template' => 'availability#approve_template', :as => :approve_template
  match 'delete_template' => 'availability#delete_template', :as => :delete_template
  match 'coach_scheduler/' => 'coach_scheduler#index', :as => :index
  match 'export_schedules_in_csv/:start_date_to_export' => 'coach_scheduler#export_schedules_in_csv', :as => :export_schedules_in_csv
  match 'coach_scheduler/:language/' => 'coach_scheduler#index', :as => :language
  match 'coach_scheduler/:language/:coach/' => 'coach_scheduler#index', :as => :language_coach
  match 'coach_scheduler/:language/:coach/:filter_language/' => 'coach_scheduler#index', :as => :language_coach_filter_language
  match 'coach_scheduler/:language/:coach/:filter_language/:date/' => 'coach_scheduler#index', :as => :language_coach_filter_language_date
  match 'coaches_for_given_language/:language/' => 'coach_scheduler#coaches_for_given_language', :as => :coaches_for_given_language
  match 'languages_for_given_language_filter' => 'schedules#languages_for_given_language_filter', :as => :languages_for_given_language_filter
  match 'topic_for_cefr_and_given_language/:language/:cefrLevel/' => 'coach_scheduler#topic_for_cefr_and_given_language', :as => :topic_for_cefr_and_given_language
  match 'create_session_form_in_coach_scheduler' => 'coach_scheduler#create_session_form_in_coach_scheduler', :as => :create_session_form_in_coach_scheduler
  match 'aria_launch_url' => 'application#aria_launch_url', :as => :aria_launch_url
  match 'create_eschool_session_from_coach_scheduler' => 'coach_scheduler#create_eschool_session_from_coach_scheduler', :as => :create_eschool_session_from_coach_scheduler
  match 'coach_session_details/:start_time/:coach_id' => 'coach_scheduler#coach_session_details', :as => :coach_session_details_manager

app/models/topic.rb
class Topic < ActiveRecord::Base
	def self.display_filtered_topic(cefrLevel = nil,language = nil,topics = {})
		where("cefr_level = ? and language = ? and removed = 0 and selected = 1", cefrLevel, language.nil? ? nil : Language[language].id).each do |t|
	      topics[t.id] = t.title
	    end
	topics
	end

	def self.fetch_topic_details(topic_id)
    topic = Topic.find(topic_id) if topic_id
    {:title => topic.title, :description => topic.description, :location => topic.cefr_level} if topic
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
   layout 'default', :only => [:index]
  # GET /topics
  # GET /topics.xml
  def index
    self.page_title = "Topics"
    @topics = Topic.where("removed = 0").order("selected = 1 desc")
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @topics }
    end
  end

  # GET /topics/new
  # GET /topics/new.xml
  def new
    @topic = Topic.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @topic }
    end
  end

  # POST /topics
  # POST /topics.xml
  def create
    @topic = Topic.new(params[:topic])
    if @topic.save
        flash[:notice] = 'Topic was successfully created.'
    else
        flash[:notice] = 'Something went wrong. Topic is not created. Please try again.'
    end
     redirect_to(:action => 'index')
  end

  # PUT /topics/1
  # PUT /topics/1.xml
  def update
    @topic = Topic.find(params[:id])
      if @topic.update_attributes(params[:topic])
       flash[:notice] = 'Topic was successfully updated.'
      else
        flash[:notice] = 'Something went wrong. Topic is not updated. Please try again.'
      end
      redirect_to(:action => 'index') 

  end

  # GET /topics/1/edit
  def edit
    @topic = Topic.find(params[:id])
  end


  # DELETE /topics/1
  # DELETE /topics/1.xml
  def destroy
    @topic = Topic.find(params[:id])
    if @topic.update_attributes(:removed => true)
      flash[:notice] = 'Topic has been hidden.'
    else
      flash[:notice] = 'Something went wrong. Topic is not hidden. Please try again.'
    end
      redirect_to(:action => 'index') 
  end


  def save_topics
    edited_topics = params[:topics_list]
    Topic.where("id in (?)",edited_topics).each do |topic|
      topic.update_attributes(:selected => !topic.selected)
    end
    render :nothing => true
  end

  # (CSP-916) Method to sync CSP data with Biblio Topics endpoint
  def update_topics
    biblio_topics = Callisto::Base.get_all_topics()
    if biblio_topics  
      count_new , count_update = 0, 0
      biblio_topics.each do |hash|
        lang = Language[TOPICS_LEARNING_LANG_CODE[hash["learningLang"]]].id
        insert_topic ={:guid => hash["id"], :revision_id => hash["revision"], :cefr_level => hash["cefrLevel"], :title => hash["title"], :language => lang, :description => hash["description"], :selected => 1}
        insert_topic.except!(:revision_id) if !hash["revision"]
        topic = Topic.find_by_guid(hash["id"])
        if topic.nil?
          Topic.create(insert_topic)
          count_new += 1
        elsif (topic.revision_id != hash["revision"])
          topic.update_attributes(insert_topic.except(:selected))
          count_update += 1
        end
      end
    flash[:notice] = "AEB Topics have been updated successfully. New: #{count_new}, Updated: #{count_update}"
    else
      flash[:error] = "Sorry, we were unable to update the Topics list. Please try again later."
    end
    redirect_to(:action => 'index')
  end
  
  def fetch_topics
  conditions = []
  lang_identifier = Language[params[:language]].id unless params[:language].empty?
  cefr_level = params[:cefr_level] unless params[:cefr_level] == "All"
  conditions << "language = '#{lang_identifier}'" if lang_identifier
  conditions << "cefr_level = '#{cefr_level}'" if cefr_level
  conditions = conditions.join(" and ")
  if conditions.empty?
      @topics = Topic.where("removed = 0").order("selected = 1 desc")
  else
      conditions << " and removed = 0"
      @topics = Topic.where(conditions).order("selected = 1 desc")
  end

  render(:update){|page| page.replace_html 'topics_list' , :partial => "topics_list.html.erb"}
  end
end

app/views/topics/_form.html.erb
<div id="error_div" class="error" style ="display:none"></div>
<%= form_for @topic , :html => { :id => 'topics_form', :multipart => true } do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% @topic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <p class="subnote">Fields labeled with <i>*</i> are required.</p>
  <div class="formfield">
  <div class="field">
    <%= f.label :guid, "GUID"%><br />
    <%= f.text_field :guid %>
  </div>
  </div>
  <div class="formfield">
  <div class="field">
    <span class="required">*</span>
    <%= f.label :title, "Title", :size =>"45" %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <span class="required">*</span>
    <%= f.label :description, "Description" %>
    <%= f.text_area :description ,:size => "45x8"%>
  </div>
  <div class="field">
    <span class="required">*</span>
    <%= f.label :language, "Language" %>
    <%= f.select :language, options_for_aria(@topic.language) -%>
  </div>
  <div class="field">
    <span class="required">*</span>
    <%= f.label :cefr_level, "CEFR Level" %><%= f.select :cefr_level, options_for_cefr(@topic.cefr_level,'-CEFR level-') -%>
    
  </div>
  <div class="field">
    <%= f.label :selected, "Active" %>
    <%= f.check_box :selected ,:checked => @topic.selected %>
  </div>
  <div class="actions">
    <input id="save" type="button" value="Save" onclick = "validateAndSave();" style="margin-left: 130px; padding :3px 20px;" />
  </div>
 </div>
<% end %>

app/views/topics/_topics_list.html.erb
<div id = 'topic_list_table_div'><br>
 <% if @topics && @topics.size > 0%>
  <table class = 'table_list scrollTable' id = 'topic_list_table'>
    <thead class = 'fixedHeader'>
    <tr>
    <th class = 'old_th204'>GUID</th>
    <th class = 'old_th174'>Title</th>
    <th class = 'old_th354'>Description </th>
    <th class = 'old_th89'>Language </th>
    <th class = 'old_th54'>Level </th>
    <th class = 'old_th78'>Action </th>
    </tr>
    </thead>
    <tbody class = 'scrollContent' id = 'scrollContent' >
      <% @topics.each do |topic| %>
      <tr id = "<%= topic.id %>">
        <td class = 'tb200'> <%= topic.guid %> </td>
        <td class= 'tb170'><%= link_to_function "#{topic.title}", "fixedFaceBoxWithHeader('#{edit_topic_path(topic)}', 'Edit Topic Details')" %></td>
        <td class= 'tb350'><%=topic.description%></td>
        <td class= 'tb85'><%=Language[topic.language].try(:identifier)%></td>
        <td class= 'tb50'><%=topic.cefr_level%></td>
        <td class= 'tb57'>
          <input class = "topics_list" type="checkbox" id=<%= topic.id %> <%= 'checked=checked' if topic[:selected] %>  />&nbsp;&nbsp;
          <%= link_to image_tag('hide.png', :size => '24x17' ,:alt => "Hide", :title => "Hide"), topic, :confirm => "Are you sure to hide the topic - #{topic.title}?", :method => :Delete %>
        </td>
      </tr>
      <%end%>
    </tbody>
  </table>
  
  <% else %>  No Topics available for the selected filter(s)

  <%end%><br /><br />

  <div class = 'topic_list_tray'>
    <%= link_to "Update", update_topics_path, :id=>"update_topics_list", :class => "button" %> &nbsp;&nbsp;&nbsp;&nbsp;
    <%= link_to_function "Add new topic", "fixedFaceBoxWithHeader('#{new_topic_path}', 'Create New Topic')", :class => "button" %>
    <%= link_to "Save" , 'javascript:void(0);', :class => "button", :id => "save_topics_list", :style => "float:right;" if @topics && @topics.size > 0 %>
  </div>

app/views/topics/edit.html.erb
<%= render 'form' %>

app/views/topics/index.html.erb
<div class="selection_container">
      <span class="selector">
       Language : <%= select_tag :lang_identifier, options_for_aria(nil,"report_page"), :onchange=>"fetch_topics()" %>
      </span>
      <span class="selector">
       CEFR : <%= select_tag :cefr_levels, options_for_cefr("All","All"), :onchange=>"fetch_topics()"  %>
      </span>
  </div>
<div id ="topics_list">
   <%= render 'topics_list' %>
</div>
<%= javascript_include_tag "topics" %>

app/views/topics/new.html.erb
<%= render 'form' %>

app/views/topics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Biblio:</b>
  <%= @topic.guid %>
</p>

<p>
  <b>Title:</b>
  <%= @topic.title %>
</p>

<p>
  <b>Description:</b>
  <%= @topic.description %>
</p>

<p>
  <b>Cefr level:</b>
  <%= @topic.cefr_level %>
</p>

<p>
  <b>Language:</b>
  <%= @topic.language %>
</p>

<p>
  <b>Selected:</b>
  <%= @topic.selected %>
</p>


<%= link_to 'Edit', edit_topic_path(@topic) %> |
<%= link_to 'Back', topics_path %>