config/routes.rb
  match 'homes/:action' => 'extranet/homes#(?i-mx:[a-z_]+)'
  match '/learner_details' => 'extranet/learners#learner_details', :as => :learner_details
  match '/show_reason_in_sub_report' => 'substitution#show_reason_in_sub_report', :as => :show_reason_in_sub_report
  match '/consumables_report' => 'support_user_portal/licenses#consumables_report', :as => :consumables_report
  match '/grandfathering_report' => 'support_user_portal/licenses#grandfathering_report', :as => :grandfathering_report
  match '/get_grandfathering_report' => 'support_user_portal/licenses#get_grandfathering_report'
  match '/download_grandfathering_report_csv' => 'support_user_portal/licenses#download_grandfathering_report_csv'
  match 'save_topics' => 'topics#save_topics', :as => :save_topics
  match 'fetch_topics' => 'topics#fetch_topics', :as => :fetch_topics
  scope :module => "extranet" do
    match 'learners/my_calendar' => 'learners#my_calendar'
    match 'events/calendar' => 'events#calendar'
    resources :learners
    resources :homes
    resources :roles
    resources :links
    resources :events
    resources :announcements
    resources :resources
    match 'learners/:action' => 'learners#(?i-mx:[a-z_]+)'
    match 'announcements/:action' => 'announcements#(?i-mx:[a-z_]+)'
    match 'events/:action' => 'events#(?i-mx:[a-z_]+)'
    match 'roles/:action' => 'roles#(?i-mx:[a-z_]+)'
    match 'links/:action' => 'links#(?i-mx:[a-z_]+)'
    match '/profile' => 'homes#view_profile', :as => :profile
    match 'homes/audit_logs' => 'homes#audit_logs', :as => :home_audit_logs
    match 'homes/track_users' => 'homes#track_users', :as => :home_track_users
    match 'homes/admin_dashboard' => 'homes#admin_dashboard', :as => :home_admin_dashboard
    match 'homes/release_lock' => 'homes#release_lock', :as => :home_release_lock
    match 'homes/simulate_delayed_job' => 'homes#simulate_delayed_job', :as => :home_simulate_delayed_job
    match 'homes/set_global_settings' => 'homes#set_global_settings', :as => :home_set_global_settings
    match 'selected_learner_chat_history' => 'learners#selected_learner_chat_history', :as => :selected_chat_history
    match 'detailed_chat_history' => 'learners#detailed_chat_history', :as => :detailed_chat_history
    resources :regions
    match 'regions/:action' => 'regions#(?i-mx:[a-z_]+)'
    resources :learners, :only => [:show] do
      member do
        get :rworld_social_app_info
      end
    end
  end
  match '/sync_eschool_csp_data' => 'application#sync_eschool_csp_data', :as => :sync_eschool_csp_data
  match '/course_info_detail' => 'extranet/learners#course_info_detail', :as => :course_info_detail
  match '/audit_logs' => 'extranet/learners#audit_logs', :as => :audit_logs
  match '/learner/:id(/learner_studio_history/:view_access)' => 'extranet/learners#learner_studio_history', :as => :learner_studio_history
  match 'learner/:id/change_password' => 'extranet/learners#change_password', :as => :change_password
  match 'resources/:action' => 'extranet/resources#(?i-mx:[a-z_]+)'
  match 'resource/:id/download_file' => 'extranet/resources#download_file', :as => :download_file
  match 'get_learner_details' => 'application#get_learner_details', :as => :get_learner_details
  match 'update_aria_session_with_slot_id' => 'application#update_aria_session_with_slot_id', :as => :update_aria_session_with_slot_id
  match 'lotus_real_time_data' => 'lotus#lotus_real_time_data', :as => :lotus_real_time_data
  match 'last_5_logins' => 'lotus#last_5_logins', :as => :last_5_logins
  match 'logged_in_history' => 'extranet/learners#logged_in_history', :as => :logged_in_history
  match 'about_lotus_data' => 'lotus#about_lotus_data', :as => :about_lotus_data
  match 'about_report_data' => 'report#about_report_data', :as => :about_report_data
  match 'learner_search_info' => 'extranet/learners#learner_search_info', :as => :learner_search_info
  match 'reflex_coach_details' => 'lotus#reflex_coach_details', :as => :reflex_coach_details
  match 'reflex_coach_scheduled_details' => 'lotus#reflex_coach_scheduled_details', :as => :reflex_coach_scheduled_details
  match 'reflex_learner_details' => 'lotus#reflex_learner_details', :as => :reflex_learner_details
  match 'activate_deactivate_license' => 'support_user_portal/licenses#activate_deactivate_license', :as => :activate_deactivate_license
  match 'learners_waiting_details' => 'lotus#learners_waiting_details', :as => :learners_waiting_details
  match 'application-status' => 'application#application_status', :as => :application_status
  match 'substitutions_alert' => 'substitution#substitutions_alert', :as => :substitutions_alert
  match 'application_configuration' => 'application#application_configuration', :as => :application_configuration
  match 'schedules/' => 'schedules#index', :as => :schedules
  match 'master-scheduler/' => 'schedules#index', :as => :master_scheduler
  match 'schedules/:language/' => 'schedules#language_schedules', :as => :language
  match 'schedules/:language/:village/' => 'schedules#language_schedules', :as => :language_and_village
  match 'schedules/:language/:village/:date/' => 'schedules#language_schedules', :as => :language_and_village_and_start_date
  match 'schedules/:language/:village/:date/:classroom_type' => 'schedules#language_schedules', :as => :language_and_village_and_start_date
  match 'slots/:language_id/:village_id/:start_time/' => 'schedules#slot_info', :as => :slot_info
  match 'create_session/:lang_identifier/:ext_village_id/:start_time' => 'schedules#create_session', :as => :create_session
  match 'schedules_coach_availability/:language/:coach/:date' => 'schedules#coach_availability_for_week', :as => :coach_availability
  match 'save_local_session' => 'schedules#save_local_session', :as => :save_local_session
  match 'extra_session_reflex/:language/:ext_village_id/:start_time' => 'schedules#extra_session_reflex', :as => :extra_session_reflex
  match 'save_extra_session' => 'schedules#save_extra_session', :as => :save_extra_session
  match 'delete_local_session' => 'schedules#delete_local_session', :as => :delete_local_session
  match 'edit_session' => 'schedules#edit_session', :as => :edit_session
  match 'remove_lotus_session' => 'schedules#remove_lotus_session', :as => :remove_lotus_session
  match 'edit_extra_session' => 'schedules#edit_extra_session', :as => :edit_extra_session
  match 'edit_extra_session_totale' => 'schedules#edit_extra_session_totale', :as => :edit_extra_session_totale
  match 'push_sessions_to_eschool' => 'schedules#push_sessions_to_eschool', :as => :push_sessions_to_eschool
  match 'save_assign_sub' => 'schedules#save_assign_sub', :as => :save_assign_sub
  match 'edit_extra_session_reflex' => 'schedules#edit_extra_session_reflex', :as => :edit_extra_session_reflex
  match 'update_extra_session_reflex' => 'schedules#update_extra_session_reflex', :as => :update_extra_session_reflex
  match 'edit_reflex_session_details' => 'schedules#edit_reflex_session_details', :as => :edit_reflex_session_details
  match 'save_edited_session' => 'schedules#update_session', :as => :save_edited_session
  match 'cancel_totale_session' => 'schedules#cancel_totale_session', :as => :cancel_totale_session
  match 'view_session_details' => 'schedules#view_session_details', :as => :view_session_details
  match 'get_learner_info' => 'schedules#get_learner_info', :as => :get_learner_info
  match 'check_recurrence_end_date' => 'schedules#check_recurrence_end_date', :as => :check_recurrence_end_date
  match 'availability' => 'availability#index', :as => :index
  match 'availability/:coach_id/' => 'availability#index', :as => :index
  match 'availability/:coach_id/:template_id' => 'availability#index', :as => :index
  match 'load_template' => 'availability#load_template', :as => :load_template
  match 'save_template' => 'availability#save_template', :as => :save_template
  match 'approve_template' => 'availability#approve_template', :as => :approve_template
  match 'delete_template' => 'availability#delete_template', :as => :delete_template
  match 'coach_scheduler/' => 'coach_scheduler#index', :as => :index
  match 'export_schedules_in_csv/:start_date_to_export' => 'coach_scheduler#export_schedules_in_csv', :as => :export_schedules_in_csv
  match 'coach_scheduler/:language/' => 'coach_scheduler#index', :as => :language
  match 'coach_scheduler/:language/:coach/' => 'coach_scheduler#index', :as => :language_coach
  match 'coach_scheduler/:language/:coach/:filter_language/' => 'coach_scheduler#index', :as => :language_coach_filter_language
  match 'coach_scheduler/:language/:coach/:filter_language/:date/' => 'coach_scheduler#index', :as => :language_coach_filter_language_date
  match 'coaches_for_given_language/:language/' => 'coach_scheduler#coaches_for_given_language', :as => :coaches_for_given_language
  match 'languages_for_given_language_filter' => 'schedules#languages_for_given_language_filter', :as => :languages_for_given_language_filter
  match 'topic_for_cefr_and_given_language/:language/:cefrLevel/' => 'coach_scheduler#topic_for_cefr_and_given_language', :as => :topic_for_cefr_and_given_language
  match 'create_session_form_in_coach_scheduler' => 'coach_scheduler#create_session_form_in_coach_scheduler', :as => :create_session_form_in_coach_scheduler
  match 'aria_launch_url' => 'application#aria_launch_url', :as => :aria_launch_url
  match 'create_eschool_session_from_coach_scheduler' => 'coach_scheduler#create_eschool_session_from_coach_scheduler', :as => :create_eschool_session_from_coach_scheduler
  match 'coach_session_details/:start_time/:coach_id' => 'coach_scheduler#coach_session_details', :as => :coach_session_details_manager
  match 'coach_session_details/:start_time' => 'coach_scheduler#coach_session_details', :as => :coach_session_details_coach
  match 'edit_coach_session' => 'coach_scheduler#edit_session_for_coach', :as => :edit_session_for_coach

app/models/locos/lotus.rb
module Locos
  class Lotus
    include RosettaStone::YamlSettings
    yaml_settings(:config_file => 'locos.yml', :hash_reader => false)
    
    class << self

      def find_learners_in_dts
        within_locos_rescuer do
          http = SimpleHTTP::Client.new settings[:locos]
          response = http.get('/app_metrics/active_session_count')
          response.body.to_i
        end
      end
      
      def find_active_session_details_by_activity
        within_locos_rescuer do
          http = SimpleHTTP::Client.new settings[:locos]
          response = http.get('/app_metrics/active_session_details_by_activity_2')
          raise Exception.new("LoCoS did not respond well!") if !response.success?
          ActiveSupport::JSON.decode response.body
        end
      end

      private

      def within_locos_rescuer
        begin
          yield if block_given?
        rescue Exception => ee
          HoptoadNotifier.notify(ee)
          return nil
        end
      end
      
    end
  end
end

app/controllers/lotus_controller.rb
require File.dirname(__FILE__) + '/../utils/lotus_real_time_data'

class LotusController < ApplicationController

  def learners_waiting_details
    @learners_waiting = LotusRealTimeData.lotus_real_time_data["learners_waiting"]
    render :partial => 'learners_waiting_details'
  end

  def lotus_real_time_data
    render(:partial => 'lotus_real_time_data', :locals => {:real_time_lotus_data_global => LotusRealTimeData.lotus_real_time_data,
        :coach_details_viewable => params[:coach_details_viewable]} )
  end

  def about_lotus_data
    render :partial => 'about_lotus_data'
  end

  def reflex_coach_details
    lotus_data = LotusRealTimeData.lotus_real_time_data
    @coach_names = lotus_data[params[:details_for]].sort.collect{|c| {:name => c}}
    if params[:details_for] == "paused"
      @coach_names.each do | coach |
        duration_in_seconds = (Time.now - ReflexActivity.where('coach_id = ? and event = "coach_paused"',Coach.find_by_full_name(coach[:name]).id).last.timestamp).round
        coach[:time] = "#{duration_in_seconds / 60} Min #{duration_in_seconds % 60} Secs"
      end  
    elsif params[:details_for] == "total_in_player"
      coach_scheduled = lotus_data['teachers_scheduled']
      @coach_names.each do |coach|
        coach[:not_scheduled] = !coach_scheduled.include?(coach[:name])
      end
    end  
    render :partial => 'reflex_coach_details'
  end

  def reflex_coach_scheduled_details
    coach_scheduled = LotusRealTimeData.lotus_real_time_data['teachers_scheduled']
    coach_in_player = LotusRealTimeData.lotus_real_time_data["total_in_player"]
    coach_not_in_player = coach_scheduled - coach_in_player
    coach_scheduled_in_player = coach_scheduled - coach_not_in_player
    @coaches = []
    coach_scheduled_in_player.each do |coach|
      #ReflexActivity.for_coaches(@coach_ids, @start_date, @end_date)
      coach_object = Coach.find_by_full_name(coach)
      last_logins = ReflexActivity.last_login_attempts(coach_object.id, 1)
      @coaches << {:name => coach, :in_player => true, :logins => last_logins, :coach_id => coach_object.id}
    end
    coach_not_in_player.each do |coach|
     @coaches << {:name => coach, :in_player => false}
    end
    @coaches = @coaches.sort_by{|coach| coach[:name]}
    render :partial => 'reflex_coach_scheduled_details'
  end

  def reflex_learner_details
    render :partial => 'reflex_learner_details', :locals => {:learners => LotusRealTimeData.lotus_real_time_data[params[:details_for]]}
  end

  def last_5_logins
    @last_logins = ReflexActivity.last_login_attempts(params[:coach_id])
    render :partial => "/lotus/last_5_logins"
  end

end

app/views/lotus/_about_lotus_data.html.erb
<div id="lotus_data_details">
  <div class="detail_item">
    <span class="attribute">Coaches Teaching:</span>
    <span class="description">The number of coaches currently engaged in conversation with a learner. Refreshed every 30 seconds.</span>
  </div>
  <div class="detail_item">
    <span class="attribute">Coaches Polling:</span>
    <span class="description">The number of coaches currently in the waiting room, ready to be matched with a learner. Refreshed every 30 seconds.</span>
  </div>
  <div class="detail_item">
    <span class="attribute">Coaches Not Teaching:</span>
    <span class="description">The total number of coaches who are in the system but not able to be matched because they are currently either paused,<br/>in a support room, configuring or reinitializing their player. Refreshed every 30 seconds.</span>
  </div>
  <div class="detail_item">
    <span class="attribute">Paused:</span>
    <span class="description">Coaches who have selected the pause option on the player. These coaches are temporarily not able to be matched.<br/>Refreshed every 30 seconds.</span>
  </div>
  <div class="detail_item">
    <span class="attribute">Receiving Support:</span>
    <span class="description">Coaches who are in a support room right now and so are unable to be matched. Refreshed every 30 seconds.</span>
  </div>
  <div class="detail_item">
    <span class="attribute">Configuring Player:</span>
    <span class="description">Coaches who have newly entered the player and are going through configuration steps<br/>and are not yet ready to be matched.Refreshed every 30 seconds.</span>
  </div>
  <div class="detail_item">
    <span class="attribute">Initializing Player:</span>
    <span class="description">Coaches who are in the process of either entering or returning to a matchable state.  Refreshed every 30 seconds.</span>
  </div>
  <div class="detail_item">
    <span class="attribute">Total Coaches in Player:</span>
    <span class="description">Sum total of coaches teaching, coaches polling, and coaches not teaching. Refreshed every 30 seconds.</span>
  </div>
  <div class="detail_item">
    <span class="attribute">Learners in Skills:</span>
    <span class="description">The number of Learners who have started entered Skills within the last 30 minutes.</span>
  </div>
  <div class="detail_item">
    <span class="attribute">Learners in Rehearsals:</span>
    <span class="description">The number of Learners who have started entered Rehearsal within the last 30 minutes.</span>
  </div>
  <div class="detail_item">
    <span class="attribute">Learners Waiting:</span>
    <span class="description">The average number of Learners (for JLE and KLE) who have completed Rehearsal<br/>and are waiting for a coach to start a Conversation.</span>
  </div>
  <div class="detail_item">
    <span class="attribute">Average wait time:</span>
    <span class="description">The average number of minutes, over the last 30 minutes, a learner (for JLE and KLE) has been waiting for a coach.</span>
  </div>
  <div class="detail_item">
    <span class="attribute">Longest wait time:</span>
    <span class="description">The length of time, in minutes, over the last 30 minutes, the longest waiting learner has been in queue.</span>
  </div>
  <div class="detail_item">
    <span class="attribute">Coaches Scheduled:</span>
    <span class="description">Coaches who are scheduled, in the Customer Success Portal, to teach right now.</span>
  </div>
</div>

app/views/lotus/_last_5_logins.html.erb
<div ><br>
<% @last_logins.each do | time | %>
<p align="center" style="font-size:12px!important"><%= time.in_time_zone("Eastern Time (US & Canada)").strftime("%m/%d/%y %I:%M %p") %></p>
<% end %></div>

app/views/lotus/_learners_waiting_details.html.erb
<div id="reflex_learners_details">
  <% if @learners_waiting.blank? %>
    There are no learners waiting.
  <% else %>
    <div class="learners_header_container">
      <span class="learner_header">Learner Name</span>
      <span class="learner_long_header">Waiting Duration(in minutes)</span>
    </div>
    <% @learners_waiting.each do |learner| %>
      <div class="learners_names_list">
        <span class="learner_name"><%= learner["display_name"]%></span>
        <span class="learner_long_attribute"><%= learner["waiting_duration"]%></span>
      </div>
    <%end%>
  <% end %>
</div>

app/views/lotus/_lotus_real_time_data.erb
<div id="real_lotus_real_time_data_divs" style = "visibility :hidden"> <!--hiding the reflex real time data -->
  <span style="float:left;"><a href="javascript:displayRow();"><img src="/images/next.png" id="img" alt="img" title ="Click to expand"/></a></span>
  <span class="lotus_info_button"><%= link_to_function image_tag('i_icon.gif',:alt => 'About this data' ,:title => 'About this data' ), "fixedFacebox('#{about_lotus_data_path}')" %></span>

  <div class="lotus_header">
    <span class="left_half">
      <div class="left_half_element" style="padding-left: 4px;">
        <span><%= link_to_function 'Total Coaches in Player',"fixedFacebox('#{reflex_coach_details_path(:details_for => 'total_in_player')}')" %></span>
        <span style="float: right; color: red"><%=  real_time_lotus_data_global["total_in_player"].size %></span>
      </div>
    </span>
    <span class="right_half" style="padding-left: 10px;">
      <div class="right_half_element">
        <span><%= link_to_function 'Learners waiting' ,"fixedFacebox('#{learners_waiting_details_path}')" %></span>
        <span style="float: right; color: red;"><%= real_time_lotus_data_global["learners_waiting"].size %></span>
      </div>
    </span>
  </div>

  <div id="caption_row">
    <hr/>
    <div class="lotus_details">
      <span class="left_half">
        <div class="left_half_element">
          <span><%= link_to_function 'Coaches Teaching',"fixedFacebox('#{reflex_coach_details_path(:details_for => 'teaching')}')" %></span>
          <span class="left_ele_attr"><%= real_time_lotus_data_global["teaching"].size %></span>
        </div>
        <div class="left_half_element">
          <span><%= link_to_function 'Coaches Polling',"fixedFacebox('#{reflex_coach_details_path(:details_for => 'polling')}')" %></span>
          <span class="left_ele_attr"><%= real_time_lotus_data_global["polling"].size %></span>
        </div>
        <div class="left_half_element">
          <span><%= link_to_function 'Coaches Not Teaching',"fixedFacebox('#{reflex_coach_details_path(:details_for => 'not_teaching')}')" %></span>
          <span class="left_ele_attr"><%= real_time_lotus_data_global["not_teaching"].size %></span>
        </div>
        <div class="small left_half_element">
          <span class="small_ele_value"><%= real_time_lotus_data_global["paused"].size %></span>
          <span class="small_ele_attr" ><%= link_to_function 'Paused',"fixedFacebox('#{reflex_coach_details_path(:details_for => 'paused')}')" %></span>
        </div>
        <div class="small left_half_element">
          <span class="small_ele_value"><%= real_time_lotus_data_global["in_support"].size %></span>
          <span class="small_ele_attr" ><%= link_to_function 'Receiving Support',"fixedFacebox('#{reflex_coach_details_path(:details_for => 'in_support')}')" %></span>
        </div>
        <div class="small left_half_element">
          <span class="small_ele_value"><%= real_time_lotus_data_global["calibrating"].size %></span>
          <span class="small_ele_attr" ><%= link_to_function 'Configuring Player',"fixedFacebox('#{reflex_coach_details_path(:details_for => 'calibrating')}')" %></span>
        </div>
        <div class="small left_half_element">
          <span class="small_ele_value"><%= real_time_lotus_data_global["initializing"].size %></span>
          <span class="small_ele_attr" ><%= link_to_function 'Initializing Player',"fixedFacebox('#{reflex_coach_details_path(:details_for => 'initializing')}')" %></span>
        </div>
        <div class="left_half_element">
          <span><%= link_to_function 'Total Coaches Scheduled',"fixedFacebox('#{reflex_coach_scheduled_details_path}')" %></span>
          <span class="left_ele_attr" id="coaches_scheduled"><%= real_time_lotus_data_global["teachers_scheduled"].size %></span>
        </div>
      </span>
      <span class="right_half">
        <div class="right_half_element">
          <span>Learners in Skills and Rehearsal</span>
          <span class="right_ele_attr" id="skills_rehearsals"><%= real_time_lotus_data_global["skills_or_rehearsal"].size %></span>
        </div>
        <div class="right_half_element">
          <span><%= link_to_function 'Learners in Skills', "fixedFacebox('#{reflex_learner_details_path(:details_for => 'skills')}')" %></span>
          <span class="right_ele_attr" id="skills"><%= real_time_lotus_data_global["skills"].size %></span>
        </div>
        <div class="right_half_element">
          <span><%= link_to_function 'Learners in Rehearsal', "fixedFacebox('#{reflex_learner_details_path(:details_for => 'conversations')}')" %></span>
          <span class="right_ele_attr" id="rehearsals"><%= real_time_lotus_data_global["conversations"].size %></span>
        </div>
        <div class="right_half_element">
          <span>Average wait time</span>
          <span class="right_ele_attr"><%= convert_to_minutes_and_seconds(real_time_lotus_data_global["average_learners_waiting_time_sec_for_both"]) %></span>
        </div>
        <div class="right_half_element">
          <span>Longest wait time</span>
          <span class="right_ele_attr"><%= convert_to_minutes_and_seconds(real_time_lotus_data_global["longest_learners_waiting_time_sec_for_both"]) %></span>
        </div>
        <div class="right_half_element" style="padding-top:35px">
          <span><%= link_to_function 'Coaches scheduled in the next half-hour' ,"fixedFacebox('#{reflex_coach_details_path(:details_for => 'teachers_scheduled_in_next_hour')}')" %></span>
          <span id ="coaches_scheduled_in_the_next_hour" class="right_ele_attr" ><%= real_time_lotus_data_global["teachers_scheduled_in_next_hour"].size %></span>
        </div>
      </span>
    </div>
  </div>
</div>

<script type="text/javascript">
  elem = document.getElementById("caption_row");
  elem.style.display = captionRowStatus;
  var images = document.getElementById("img");
  images.src = imageLink;
  images.title = imageTitle
</script>

app/views/lotus/_reflex_coach_details.erb
<div class ="popup_learner_container">
  <% if @coach_names.blank? %>
    <div style ="float: left" id="message">No coaches available</div>
  <% else %>
    <% if params[:details_for] == "paused" %>
      <div class="popup_coach_list_with_time">
        <table id="popup_coach_list_entries" >
          <thead>
            <tr>
              <th scope="col" style="width:200px;">Coach</th>
              <th scope="col">Time Paused</th>
            </tr>
          </thead>
          <tbody>
            <% @coach_names.each do |coach| %>
              <tr>
                <td><%= coach[:name] %></td>
                <td><%= coach[:time] %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    <% else %>
      <div class="popup_coach_list">
        <% @coach_names.each do |coach| %>
          <div class="coach_element" <% if coach[:not_scheduled] %>style = "color: red"<% end %>><%= coach[:name] %></div>
        <% end %>
      </div>
    <% end %>
  <% end %>
</div>
<%= javascript_tag do %>
  jQuery(document).ready(function() {
  setFaceboxWidth();
  });
<% end %>

app/views/lotus/_reflex_coach_scheduled_details.erb
<div class ="popup_learner_container">
	<% if @coaches.blank? %>
		<div style ="float: left"><div id="message"><%= "No coaches available" %></div></div>
	<% else %>
		<div class="popup_coach_list">
 	    	<% @coaches.each do |coach| %>  
 	        	<div class="coach_element" <% if !coach[:in_player] %>style = "color: red"<% end %>><%= coach[:name] %></div>  		
 	        <% end %>
 		</div>
 
 	<% end %>
</div>
<%= javascript_tag do %>
  jQuery(document).ready(function() {
    setFaceboxWidth();
  });
<% end %>

app/views/lotus/_reflex_coach_scheduled_details.html.erb
<div class ="popup_learner_container">
    <% if @coaches.blank? %>
        <div style ="float: left"><div id="message"><%= "No coaches available" %></div></div>
    <% else %>
        <div class="popup_coach_list_with_time">
            <table id="popup_coach_list_entries" >
                <thead>
                    <tr>
                        <th scope="col" width="200px">Coach</th>
                        <th scope="col">In Player At</th>
                    </tr>
                </thead>
                <tbody>
                    <% @coaches.each do |coach| %>
                    <tr>
                        <td <% if !coach[:in_player] %>style = "color: red"<% end %>><%= coach[:name] %></td>
                        <% if !coach[:in_player] %>
                            <td style = "color: red">Not In Player</td>
                        <% else %>
                            <td>
                                <% if coach[:logins].present? %>
                                    <a id="entry_time" coachid="<%= coach[:coach_id] %>" coachname="<%= coach[:name] %>" ><%= coach[:logins].first.in_time_zone("Eastern Time (US & Canada)").strftime("%I:%M %p") %><a>
                                <% else %>
                                    No login history found. 
                                <% end %>
                            </td>
                        <% end %>
                    </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
    <% end %>
</div>
<%= javascript_tag do %>
  jQuery(document).ready(function() {
    setFaceboxWidth();
  });
<% end %>

app/views/lotus/_reflex_learner_details.erb
<div id="reflex_learners_details">
  <% if !learners.blank? %>
    <div class="learners_header_container">
      <span class="learner_header">First Name</span>
      <span class="learner_header">Last Name</span>
      <span class="learner_header">Preferred Name</span>
    </div>
      <% learners.each do |learner| %>
        <div class="learners_names_list">
          <span class="learner_name"><%= learner["first_name"] %></span>
          <span class="learner_name"><%= learner["last_name"] %></span>
          <span class="learner_name"><%= learner["preferred_name"] %></span>
        </div>
      <% end %>
    <% else %>
    <div style ="float: left">
      <div id="message"><%= "No learners available" %></div>
    </div>
  <% end %>
</div>

<%= javascript_tag do %>
  jQuery(document).ready(function() {
    setFaceboxWidth();
  });
<% end %>